name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hola primer saludo en actions!!"
      - name: Print GoodBye
        run: echo "hasta luegooo!!"
